spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.37.174.16:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 1
    port: 6379
    timeout: 500ms
    host: 101.37.174.16
  mail:
    host: smtp.qq.com
    username: 1208549329@qq.com
    password: urqspgolqhhpggcg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
  thymeleaf:
    cache: false


aliyun:
  accessKeyId:
  secret:
logging:
  config: classpath:logback-spring.xml

